# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GDS Playground
email: davidjamesstone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GOV.UK Themed Jekyll Site
baseurl: "/gds-playground" # the subpath of your site, e.g. /blog
url: "http://davidjamesstone.github.io" # the base hostname & protocol for your site
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"

# Build settings
markdown: kramdown
